### ISSUE TITLE
Resumen

### ISSUE THREAD

**Issue by pgl1005** [Mariosutil/Ing_Gest_Poyectos#1]

**Comment by pgl1005** [comment]
Crear un resumen del capítulo 01 de máximo 300 palabras.

**Comment by pgl1005** [comment]
**Esta es mi parte del resumen del capítulo 1:**

Existen dos modelos de gestión que son la gestión ágil y la gestión de proyectos predictiva. 
Valores del manifiesto ágil:

- Valorar a los individuos y su interacción más que a los procesos y las herramientas.

- Valorar el software que funciona por encima de documentación.

- Valorar la colaboración con el cliente más que la negociación contractual.

- Valorar más la respuesta al cambio que el seguimiento del plan.

Los 12 principios del manifiesto ágil son:
Satisfacer al cliente, que existan requisitos cambiantes, entregar con frecuencia un software que funcione, los desarrolladores deben de trabajar junto con las personas del negocio, aportar confianza a los individuos para que realicen la tarea adecuadamente, que existan reuniones para comunicar la información, un software que funciona es la principal medida del progreso, que exista un ritmo constante de forma indefinida, atención continua, simplicidad, una buena organización y reflexionar para ser más eficientes.

Principales características de Scrum:
-	Equipos que comparten sus conocimientos.
-	Desarrollo incremental.
-	Calidad depende del conocimiento de las personas y de su creatividad.
-	Solapamiento de fases.

Conceptos de Scrum: 

- El desarrollo puede ser completo, o incremental.

- El trabajo puede ser secuencial o concurrente.

- El conocimiento se puede basar en los procesos o en las personas.

2 modelos de Scrum:

- La gestión predictiva, en el inicio se obtiene el resultado final del producto cumpliendo el plazo y los recursos que se acuerden.

- La gestión evolutiva, se encarga de entregar algo lo antes posible al cliente, emplea el solapamiento de las fases y se puede llevar a cabo en ingeniería concurrente o en agilidad. 

La ingeniería concurrente se centra en la calidad de los procesos. 
La agilidad se centra en el conocimiento táctico de las personas.

**Comment by Mariosutil** [comment]
Lo veo correcto Paula!!!

**Comment by JuliaArellano** [comment]
Para poder utilizar scrum de forma adecuada, es recomendable que las personas que lo vayan a utilizar primero se lean el manual porque si se el objetivo esta puesto en el proceso, sin conocimiento teóricos se perderá agilidad.

**Comment by JuliaArellano** [comment]
Para poder utilizar scrum de forma adecuada, es recomendable que las personas que lo vayan a utilizar primero se lean el manual porque si el objetivo esta puesto en el proceso, sin conocimiento teóricos se perderá agilidad.

**Comment by Mariosutil** [comment]
Perfecto, solo faltaría unir ambas partes en la Wiki.

**Comment by JuliaArellano** [comment]
Subo las partes y finalizo tarea
