### ISSUE TITLE
Preguntas de comprensión

### ISSUE THREAD

**Issue by Mariosutil** [Mariosutil/Ing_Gest_Poyectos#10]
Añadir de 1 a 5 preguntas (FAQ) acerca del capítulo 02.

**Comment by Lorenacalvoperez** [comment]
He realizado alguna pregunta de compresión sobre la parte del capítulo que me tocaba:

**1.	¿Qué es lo que se pretende conseguir con la realización de las distintas reuniones?**
Dependiendo de la reunión que se esté realizando, el objetivo es distinto, pero al fin y al cabo están enfocados a conseguir lo mismo, llevar a cabo con la mejor organización posible la elaboración de un proyecto o un producto que tiene que ser entregado a un usuario en un plazo determinado de tiempo.

**2.	¿Por qué los sprints son necesarios para la realización del scrum?**
Los sprints son en torno a los cuales se organiza todo el proyecto, cada tarea que se va realizando ya sea que esta esté abierta o cerrada. Se considera que los sprints son los núcleos fundamentales por ello partimos de ellos para la organización de absolutamente todo el proyecto.


**3.	¿Qué es lo que se analiza en la retrospectiva des sprint?**
Se analiza la manera de trabajar, por otro lado, la perspectiva del propietario de producto puede aportar mucho valor, ya que es responsable de mantener el foco en construir lo que el cliente necesita

**Comment by Mariosutil** [comment]
Las veo muy bien. Lo único Lorena, en la pregunta 3, creo que hay una errata, ¿no debería de ser "... analiza en la retrospectiva **de** sprint" en vez de "**des**"?

**Comment by pgl1005** [comment]
Muy buenas preguntas!!

**Comment by JuliaArellano** [comment]
**4. ¿Quién es el propietario del producto?**
Es el que toma las decisiones del cliente. Si el cliente es una propia empresa , este rol lo suele asumir el responsable de marketing, en desarrollos externos, suele ser el responsable del proceso de adquisición al cliente. Incluso el propietario puede delegar en el equipo o alguien de confianza.

**5. ¿Que es una pila de producto?**
Todo el trabajo necesario para obtener el producto final cumpliendo los requisitos dados por el cliente. En resumen, representa todo aquello que esperan el cliente , los usuarios y todas las demás partes interesadas.

**6. Nombra los distintos eventos posibles**
    - Sprint
    - Reunión de planificación del sprint
    - Scrum diario
    - Revisión del sprint
    - Retrospectiva del sprint

**Comment by JuliaArellano** [comment]
**4. ¿Quién es el propietario del producto?**
Es el que toma las decisiones del cliente. Si el cliente es una propia empresa , este rol lo suele asumir el responsable de marketing, en desarrollos externos, suele ser el responsable del proceso de adquisición al cliente. Incluso el propietario puede delegar en el equipo o alguien de confianza.

**5. ¿Qué es una pila de producto?**
Todo el trabajo necesario para obtener el producto final cumpliendo los requisitos dados por el cliente. En resumen, representa todo aquello que esperan el cliente , los usuarios y todas las demás partes interesadas.

**6. Nombra los distintos eventos posibles**
- Sprint
- Reunión de planificación del sprint
- Scrum diario
- Revisión del sprint
- Retrospectiva del sprint

**Comment by Lorenacalvoperez** [comment]
He realizado alguna pregunta de compresión sobre la parte del capítulo que me tocaba:

**1. ¿Qué es lo que se pretende conseguir con la realización de las distintas reuniones?**
Dependiendo de la reunión que se esté realizando, el objetivo es distinto, pero al fin y al cabo están enfocados a conseguir lo mismo, llevar a cabo con la mejor organización posible la elaboración de un proyecto o un producto que tiene que ser entregado a un usuario en un plazo determinado de tiempo.

**2. ¿Qué es lo que se analiza en la retrospectiva del sprint?**
Se analiza la manera de trabajar, por otro lado, la perspectiva del propietario de producto puede aportar mucho valor, ya que es responsable de mantener el foco en construir lo que el cliente necesita

**3. ¿Quién es el propietario del producto?**
Es el que toma las decisiones del cliente. Si el cliente es una propia empresa , este rol lo suele asumir el responsable de marketing, en desarrollos externos, suele ser el responsable del proceso de adquisición al cliente. Incluso el propietario puede delegar en el equipo o alguien de confianza.

**4. ¿Qué es una pila de producto?**
Todo el trabajo necesario para obtener el producto final cumpliendo los requisitos dados por el cliente. En resumen, representa todo aquello que esperan el cliente , los usuarios y todas las demás partes interesadas.

**5. Nombra los distintos eventos posibles**

   •	   Sprint
   •	   Reunión de planificación del sprint
   •	   Scrum diario
   •	   Revisión del sprint
   •	   Retrospectiva del sprint

**Comment by Lorenacalvoperez** [comment]
Nos quedamos finalmente con estas preguntas
