### ISSUE TITLE
Diagrama conceptual

### ISSUE THREAD

**Issue by Lorenacalvoperez** [Mariosutil/Ing_Gest_Poyectos#11]
Realizar un diagrama conceptual sobre ciertos términos del capítulo

**Comment by Mariosutil** [comment]
**He encontrado dos diagramas acerca de dos prácticas interesantes para flexibilizar scrum:**
-**ESTIMACIÓN DE PÓQUER**:
![image](https://user-images.githubusercontent.com/127235455/230569594-8590c73f-cd57-4f49-ab8a-4a0bbb0a1655.png)

-**GRÁFICO DE PRODUCTO:**
![image](https://user-images.githubusercontent.com/127235455/230571301-d7757e05-a62d-491f-ae83-b4f3b4d96a4b.png)


Ambos diagramas son bastante representativos acerca de lo que hace cada una de estas dos prácticas. Si os parece bien, podría subir los dos.

**Comment by Mariosutil** [comment]
He encontrado un diagrama que relaciona los roles en un proyecto scrum:

![image](https://user-images.githubusercontent.com/127235455/230578322-7727e83c-b0c2-4028-a869-4f375db6542f.png)


Si os gusta también lo puedo subir.

**Comment by Lorenacalvoperez** [comment]
Los tres representan muy bien lo explicado en el capítulo 03, lo veo genial!!

**Comment by Mariosutil** [comment]
Perfecto, entonces voy a cerrar la tarea.
