### ISSUE TITLE
Enlaces de Interés

### ISSUE THREAD

**Issue by pgl1005** [Mariosutil/Ing_Gest_Poyectos#12]
Añadir enlaces de interés que tengan relación con el capítulo

**Comment by pgl1005** [comment]
He encontrado esta página web en donde se hace un resumen sobre la historia de Scrum y el proyecto ágil.

[https://proyectosagiles.org/historia-de-scrum/#:~:text=El%20concepto%20de%20Scrum%20tiene,ordenadores%20de%20HP%20y%20otros](url)

**Comment by Mariosutil** [comment]
Muy interesante Paula!!!
