### ISSUE TITLE
Enlaces de interés

### ISSUE THREAD

**Issue by Mariosutil** [Mariosutil/Ing_Gest_Poyectos#13]
Añadir enlaces relacionados con el capítulo 02.

**Comment by Lorenacalvoperez** [comment]
He encontrado este enlace en relación al capítulo 02:

**Enlace relacionado con la planificación de los sprints**
https://www.atlassian.com/es/agile/scrum/sprint-planning

**Comment by JuliaArellano** [comment]
**Otro enlace con relación a los roles:** 
https://www2.deloitte.com/es/es/pages/technology/articles/roles-y-responsabilidades-scrum.html

**Comment by Mariosutil** [comment]
Buen enlace, muy interesante Julia.

**Comment by pgl1005** [comment]
Muy interesante.
