### ISSUE TITLE
Enlaces de interés

### ISSUE THREAD

**Issue by Lorenacalvoperez** [Mariosutil/Ing_Gest_Poyectos#14]
Adjuntar distintos enlaces relacionados con el capítulo

**Comment by Mariosutil** [comment]
**He encontrado estos enlaces de interés sobre el capítulo 3:**

- **Enlace sobre plantillas de diagramas para retrospectivas:**

https://miro.com/es/plantillas/herramienta-retrospectiva/ 

- **Enlace para utilizar diagrama de árbol de producto:**

https://miro.com/es/plantillas/podar-arbol-de-producto/ 

- **Enlace acerca de roles y sus responsabilidades en un proyecto scrum:**

https://www.gestiondeproyectos-master.com/roles-y-responsabilidades-en-un-proyecto-scrum/ 

¿Qué os parece?

**Comment by Lorenacalvoperez** [comment]
Me parecen muy interesantes los enlaces que has encontrado!!

**Comment by Mariosutil** [comment]
Perfecto, procedo a cerrar la tarea.
