### ISSUE TITLE
Preguntas de compresión

### ISSUE THREAD

**Issue by JuliaArellano** [Mariosutil/Ing_Gest_Poyectos#15]
realizar preguntas de compresión

**Comment by Mariosutil** [comment]
**He realizado algunas preguntas de comprensión (FAQ):**

**1. ¿Por qué se recomienda el rol de Scrum Master en una empresa grande con rotación del personal?**

Porque garantiza que el marco scrum funcione gracias a que modera las reuniones diarias donde se resuelven los distintos impedimentos y consigue que el equipo avance.


**2. ¿En el marco scrum podríamos centrarnos únicamente en las herramientas?**

No, sería un error puesto que sin una base que se asiente en unos principios y valores scrum solo se conseguiría una lenta organización y unos mediocres resultados por parte del equipo.


**3. ¿Es importante actualizar el Gráfico Burn Down diariamente?**

Sí, es importante porque en este gráfico se refleja el esfuerzo pendiente de todas las tareas sin terminar. En el eje Y se representan los puntos de trabajo que no se han realizado y en el eje X los días del sprint; así en la diagonal queda reflejado el avance de un sprint.


**4. ¿Qué indica el WIP en la técnica Kanban?**

El WIP (Work In Process) indica el número máximo de tareas que pueden estar a la vez en la misma fase del proceso y en las que el equipo puede trabajar simultáneamente. 


**5. ¿Los Diagramas de Árbol son todos iguales?**
No son todos iguales porque no existe un diagrama estándar de árbol, sino que hay múltiples, como el desarrollado por Khurram Bhatti.

**Comment by Lorenacalvoperez** [comment]
Muy interesantes tus preguntas!!

**Comment by Mariosutil** [comment]
Perfecto, muchas gracias. Procedo entonces a cerrar mi tarea.
