### ISSUE TITLE
Resumen 

### ISSUE THREAD

**Issue by Mariosutil** [Mariosutil/Ing_Gest_Poyectos#2]
Hacer un resumen de 300 palabras máximo acerca del capítulo.

**Comment by Lorenacalvoperez** [comment]
Voy a comenzar a realizarlo

**Comment by Lorenacalvoperez** [comment]
Este es el resumen de mi parte del capítulo:

El incremento se produce en el sprint y se entrega al cliente. El primer sprint ("sprint cero"), inicia el proyecto. El objetivo es conseguir la calidad esperada del producto y que el equipo concluya el proyecto de forma común.
Los eventos son:

>1.	La rutina de trabajo en scrum consta de sprints que son núcleos fundamentales. Las tareas tienen ritmo y tiempo fijo.

2.	Reunión de planificación del sprint:
•	Marca su inicio indicando su objetivo
•	Avanza ritmo constante. 
•	Primera mitad: el propietario expone las necesidades del proyecto, si hay cambios posteriormente se explican las causas. 
•	Segunda mitad: se asignan tareas. Cada tarea se ordena por prioridad y esfuerzo. Quedará organizado diariamente.
3.	Scrum diario: reunión para verificar los avances del proyecto, informando sobre las tareas de cada uno. Finalmente, será revisado. El grafico indicará qué tareas están siendo realizadas y por quien incluyendo el tiempo de realización.
4.	Retrospectiva del sprint: reunión al finalizar el sprint creando y aplicando un plan de mejoras.
5.	Revisión del sprint: reunión informal final para enseñar el incremento y recoger sugerencias. Exponiendo el objetivo del sprint y demostrando el funcionamiento de cada parte. 
Para planificar mejor consideramos el trabajo restante empleando unidades relativas. Dependiendo de quien realice la tarea el tiempo será distinto.
El significado y la métrica debe de ser la misma en las mediciones de organización según el tipo de organización.
El sprint se divide según el tiempo de trabajo en condiciones ideales, no tiene por qué ser real sino una estimación.

**Comment by Lorenacalvoperez** [comment]
El incremento se produce en el sprint y se entrega al cliente. El primer sprint ("sprint cero"), inicia el proyecto. El objetivo es conseguir la calidad esperada del producto y que el equipo concluya el proyecto de forma común.
Los eventos son:
1.	La rutina de trabajo en scrum consta de sprints que son núcleos fundamentales. Las tareas tienen ritmo y tiempo fijo.
2.	Reunión de planificación del sprint:
•	Marca su inicio indicando su objetivo
•	Avanza ritmo constante. 
•	Primera mitad: el propietario expone las necesidades del proyecto, si hay cambios posteriormente se explican las causas. 
•	Segunda mitad: se asignan tareas. Cada tarea se ordena por prioridad y esfuerzo. Quedará organizado diariamente.
3.	Scrum diario: reunión para verificar los avances del proyecto, informando sobre las tareas de cada uno. Finalmente, será revisado. El grafico indicará qué tareas están siendo realizadas y por quien incluyendo el tiempo de realización.
4.	Retrospectiva del sprint: reunión al finalizar el sprint creando y aplicando un plan de mejoras.
5.	Revisión del sprint: reunión informal final para enseñar el incremento y recoger sugerencias. Exponiendo el objetivo del sprint y demostrando el funcionamiento de cada parte. 
Para planificar mejor consideramos el trabajo restante empleando unidades relativas. Dependiendo de quien realice la tarea el tiempo será distinto.
El significado y la métrica debe de ser la misma en las mediciones de organización según el tipo de organización.
El sprint se divide según el tiempo de trabajo en condiciones ideales, no tiene por qué ser real sino una estimación.

**Comment by JuliaArellano** [comment]
Los componentes del ciclo estándar de scrum son: 
 • Equipo scrum:
 • Desarrollador: se encargan de realizar el incremento de cada sprint.
• Propietario del producto: Es quien toma las decisiones del cliente (ya que conoce sus necesidades), se encarga de controlar que se cumpla el objetivo en plazo.
• Scrum máster: se encarga del comprobar el cumplimiento de las reglas de scrum.
• Artefactos:
 • Pila del producto: muestras los requisitos y da les da prioridad en función del punto de vista del cliente.
 Pila del sprint: es la lista de todas las tareas necesarias para cumplir los requisitos del cliente de cada sprint, se realiza por los desarrolladores.
 • Incremento. 
• Eventos: 
• Sprint.
 • Reunión de planificación del sprint.
 • Scrum diario.
 • Revisión y retrospectiva del sprint.

**Comment by JuliaArellano** [comment]
Los componentes del ciclo estándar de scrum son: 
 • Equipo scrum:
 • Desarrollador: se encargan de realizar el incremento de cada sprint.
• Propietario del producto: Es quien toma las decisiones del cliente (ya que conoce sus necesidades), se encarga de controlar que se cumpla el objetivo en plazo.
• Scrum máster: se encarga del comprobar el cumplimiento de las reglas de scrum.
• Artefactos:
 • Pila del producto: muestras los requisitos y da les da prioridad en función del punto de vista del cliente.
• Pila del sprint: es la lista de todas las tareas necesarias para cumplir los requisitos del cliente de cada sprint, se realiza por los desarrolladores.
 • Incremento. 
• Eventos: 
• Sprint.
 • Reunión de planificación del sprint.
 • Scrum diario.
 • Revisión y retrospectiva del sprint.

**Comment by Lorenacalvoperez** [comment]
Los componentes del ciclo estándar de scrum son:
•	Equipo scrum
•	Desarrollador: se encargan de realizar el incremento de cada sprint.
•	Propietario del producto: Es quien toma las decisiones del cliente (ya que conoce sus necesidades), se encarga de controlar que se cumpla el objetivo en plazo.
•	Scrum máster: se encarga del comprobar el cumplimiento de las reglas de scrum.
•	Artefactos
•	Pila del producto: muestras los requisitos y da les da prioridad en función del punto de vista del cliente.
•	Pila del sprint: es la lista de todas las tareas necesarias para cumplir los requisitos del cliente de cada sprint, se realiza por los desarrolladores.
•	Incremento: se produce en el sprint y se entrega al cliente. El primer sprint ("sprint cero"), inicia el proyecto. El objetivo es conseguir la calidad esperada del producto.
•	Eventos:
	Sprint: núcleo fundamental de scrum.
	Reunión de planificación del sprint: Marca su inicio indicando su objetivo. El propietario expone las necesidades y si hay cambios se explican las causas. Se asignan tareas. Cada tarea se ordena por prioridad y esfuerzo.
	Scrum diario: reunión para verificar los avances del proyecto, informando sobre las tareas de cada uno. Finalmente, será revisado.
	Retrospectiva del sprint: reunión al finalizar el sprint creando y aplicando un plan de mejoras.
	Revisión del sprint: reunión informal final para enseñar el incremento y recoger sugerencias. Exponiendo el objetivo del sprint y demostrando el funcionamiento de cada parte. 
Dependiendo de quien realice la tarea el tiempo será distinto. El sprint se divide según el tiempo de trabajo en condiciones ideales, no tiene por qué ser real sino una estimación.

**Comment by Lorenacalvoperez** [comment]
Los componentes del ciclo estándar de scrum son:
•	Equipo scrum
•	Desarrollador: se encargan de realizar el incremento de cada sprint.
•	Propietario del producto: Es quien toma las decisiones del cliente (ya que conoce sus necesidades), se encarga de controlar que se cumpla el objetivo en plazo.
•	Scrum máster: se encarga del comprobar el cumplimiento de las reglas de scrum.
•	Artefactos
•	Pila del producto: muestras los requisitos y da les da prioridad en función del punto de vista del cliente.
•	Pila del sprint: es la lista de todas las tareas necesarias para cumplir los requisitos del cliente de cada sprint, se realiza por los desarrolladores.
•	Incremento: se produce en el sprint y se entrega al cliente. El primer sprint ("sprint cero"), inicia el proyecto. El objetivo es conseguir la calidad esperada del producto.
•	Eventos:
	Sprint: núcleo fundamental de scrum.
	Reunión de planificación del sprint: Marca su inicio indicando su objetivo. El propietario expone las necesidades y si hay cambios se explican las causas. Se asignan tareas. Cada tarea se ordena por prioridad y esfuerzo.
	Scrum diario: reunión para verificar los avances del proyecto, informando sobre las tareas de cada uno. Finalmente, será revisado.
	Retrospectiva del sprint: reunión al finalizar el sprint creando y aplicando un plan de mejoras.
	Revisión del sprint: reunión informal final para enseñar el incremento y recoger sugerencias. Exponiendo el objetivo del sprint y demostrando el funcionamiento de cada parte. 
Dependiendo de quien realice la tarea el tiempo será distinto. El sprint se divide según el tiempo de trabajo en condiciones ideales, no tiene por qué ser real sino una estimación.

**Comment by JuliaArellano** [comment]
Inicialmente se visualiza de forma general el resultado y después se describe a detalle las funciones y como se va a organizar los eventos y la duración de cada uno de ellos.
Los componentes del ciclo estándar de scrum son:
**Equipo scrum** 
A cada integrante se le asigna un rol y este se va encargar de autogestionarse sus tareas pero teniendo en cuenta que todos los integrantes deben colaborar siendo comprometidos e implicados.
• Desarrollador: se encarga de realizar el incremento de cada sprint.
• Propietario del producto: es quien toma las decisiones del cliente (ya que conoce sus necesidades), se encarga de controlar que se cumpla el objetivo en plazo.
• Scrum máster: se encarga del comprobar el cumplimiento de las reglas de scrum.
**Artefactos**
• Pila del producto: muestra los requisitos y da les da prioridad en función del punto de vista del cliente.
• Pila del sprint: es la lista de todas las tareas necesarias para cumplir los requisitos del cliente de cada sprint, se realiza por los desarrolladores.
• Incremento: es la parte del producto que se produce en cada sprint y que se entrega al cliente. El primer sprint ("sprint cero"), inicia el proyecto. El objetivo es conseguir la calidad esperada del producto. 
 **Eventos**
• Sprint: núcleo fundamental de scrum. Es un periodo de tiempo acotado durante el cual se construye un incremento del producto. El sprint se divide según el tiempo de trabajo en condiciones ideales, no tiene por qué ser real sino una estimación.
• Reunión de planificación del sprint:  Es una reunión que marca los objetivos de cada sprint. El propietario expone las necesidades y si hay cambios se explican las causas. Se asignan tareas y se ordenan por prioridad y esfuerzo.
• Scrum diario: es la reunión para verificar los avances del proyecto, informando sobre las tareas de cada integrante que finalmente, será revisado.
• Retrospectiva del sprint: es una reunión que se realiza al finalizar el sprint creando y aplicando un plan de mejoras.
• Revisión del sprint: es una reunión informal final para enseñar el incremento y recoger sugerencias, exponiéndose el objetivo del sprint y demostrando el funcionamiento de cada parte.

Además, scrum nos permite trabajar en varias tareas a la vez y avanzar de forma simultanea

**Comment by Lorenacalvoperez** [comment]
Finalmente ha quedado perfecto!!

**Comment by Lorenacalvoperez** [comment]
Lo coloco en la wiki y tarea completada
