### ISSUE TITLE
Resumen

### ISSUE THREAD

**Issue by Lorenacalvoperez** [Mariosutil/Ing_Gest_Poyectos#3]
Realizar un resumen de un total máximo de 300 palabras sobre el capítulo.

**Comment by Mariosutil** [comment]
**Este es mi resumen del capítulo 3:**

Los modelos de gestión llevan a desarrollar unos principios de trabajo y valores de organización que deben ser flexibles para adaptarse a las diversas empresas y proyectos, sin olvidar que una buena gestión busca utilizar las más modernas herramientas, pero adecuándolas al equipo de cada empresa. 

Los **principios** que forman el soporte de las prácticas son:
•	Entrega de valor
•	Mejora continua
•	Desarrollo iterativo e incremental
•	Ritmo de trabajo sostenible
•	Atención continua a la excelencia
•	Operativa visible
•	Cadencia y sincronización global

Las características de organización y gobernanza forman la **cultura de empresa**, que frena o acelera su ágil desarrollo. La dirección debe seguir los mismos valores, apoyando a su personal comprometido y con talento.

Existen varios **roles**:
•	Propietario del Producto: representa al cliente y lo que quiere, y es el responsable de la pila del producto.
•	Desarrolladores: con su talento e inteligencia colectiva deben mejorar sus resultados y métodos en beneficio del cliente.
•	Scrum master: es quien, con diversas reuniones para resolver los distintos impedimentos, consigue que el equipo avance y funcione en el marco scrum. 

Estos roles asumen los distintos **artefactos** (pilas del producto y del sprint, incremento) y **eventos** (sprint, reunión de planificación del sprint, scrum diario, revisión y retrospectiva del sprint) que ayudan a desarrollar los principios ágiles. 

Un equipo personaliza su proyecto aplicando diversas **prácticas**, que agilizan su gestión. Entre ellas destaca el _Gráfico Burn Down_ o _Gráfico de Avance_, que permite detectar desviaciones tempranamente. Así como la _Estimación de Póquer_, que dinamiza las reuniones y consigue consensos sin discusiones sobre las tareas y su duración, la más usada es la baraja con números en sucesión de Fibonacci. 

Otras prácticas utilizadas son: _Estimación sin puntos de historia_, _Kanban_, _Trabajo en pareja_, _Gráfica del producto_, _Diagramas para retrospectivas en espina de pez o árbol_, etc.

**Comment by JuliaArellano** [comment]
todo correcto

**Comment by JuliaArellano** [comment]
Uns vez que este subido a la Wiki cierro tarea

**Comment by Mariosutil** [comment]
Procedo a cerrarla.
