### ISSUE TITLE
Glosario de términos

### ISSUE THREAD

**Issue by pgl1005** [Mariosutil/Ing_Gest_Poyectos#4]
Escribir un glosario con las palabras más importantes del capítulo

**Comment by pgl1005** [comment]
Estos son los términos más importantes del capítulo 1:

-	**Gestión predictiva:** disciplina que trata de la planificación, organización, seguimiento y control de los aspectos de un proyecto para alcanzar los objetivos. Realiza el uso más eficiente de los recursos para cumplir plazos costes y calidad.

-	**Gestión evolutiva:** conjunto de técnicas y prácticas empleadas para conducir la ejecución progresiva de un proyecto de forma que genere un mínimo producto viable en el menor tiempo posible, y a partir de una primera entrega, exista un incremento continuo del producto.

-	**Desarrollo iterativo e incremental:** en cada iteración el equipo evoluciona el producto a partir de las iteraciones anteriores.

-	**Empresas del conocimiento:** empresas que desarrollan productos basándose en el conocimiento más que en las herramientas y procesos.

-	**Crisis del software**: conjunto de dificultades o errores ocurridos en la planificación productividad o calidad del software. hoy se utilizaba este término para dar solución a los problemas que se presentaban en la primera conferencia elaborada por la OTAN.

-	**Ingeniería del software:** rama de ingeniería encargada del estudio de los principios y metodologías para el desarrollo y mantenimiento de sistemas software. 

-	**Scrum:** marco de gestión de proyectos de metodología ágil que ayuda a los equipos a estructurar y gestionar el trabajo mediante un conjunto de valores principios y prácticas. 

-	**Timeboxing:** estrategia de gestión del tiempo orientada a los objetivos que pueden ayudarte a aumentar la productividad.

**Comment by Lorenacalvoperez** [comment]
Está todo perfecto!!
