### ISSUE TITLE
Glosario de términos

### ISSUE THREAD

**Issue by Mariosutil** [Mariosutil/Ing_Gest_Poyectos#5]
Realizar un glosario de contenidos acerca del capitulo 2 (máximo 15 términos).

**Comment by Lorenacalvoperez** [comment]
Este es el glosario de términos de mi parte del capítulo:

**Revisión del sprint:** es el análisis e inspección del «incremento» generado, y adaptación de la pila del producto si resulta necesario.

**Sprint:** es el núcleo fundamental de scrum, en torno al que se organizan todos los demás. A veces se llama también «iteración». Es el nombre que recibe cada etapa de trabajo con un objetivo concreto dentro del proyecto. La división del trabajo en sprints, que tienen una duración fija y constante que permite mantener el ritmo de avance.

**Scrum diario:** es una reunión diaria breve, de no más de 15 minutos, en la que los desarrolladores sincronizan el trabajo y establecen el plan para las 24 horas siguientes

**Incremento:** es la parte de producto producida en un sprint y que se encuentra en condiciones de ser entregada al cliente; es decir: terminada, probada y operativa. No se deben considerar incrementos a prototipos, módulos o ni a partes pendientes de pruebas.

**Ámbito del sprint:** se considera sólo la construcción del incremento, dejando a un lado las reuniones. 

**Propietario del producto:** es la persona que se encarga de exponer en qué forma el producto puede incrementar su valor con el resultado del sprint que se va a realizar.

**Comment by pgl1005** [comment]
Lo veo genial.

**Comment by JuliaArellano** [comment]
Grupo de trabajo: las personas tienen una asignación específica de
tareas, responsabilidades, y siguen un proceso o pautas de ejecución. Los
operarios de una cadena forman un grupo de trabajo; aunque tienen un jefe
común, y trabajan en la misma organización, cada uno responde de forma
individual.

**Comment by JuliaArellano** [comment]
Grupo de trabajo: las personas tienen una asignación específica de
tareas, responsabilidades, y siguen un proceso o pautas de ejecución. Los
operarios de una cadena forman un grupo de trabajo; aunque tienen un jefe
común, y trabajan en la misma organización, cada uno responde de forma
individual.
Equipo: Un equipo tiene espíritu de colaboración y un propósito común: conseguir
el mayor valor posible para la visión del cliente. Los desarrolladores se
autogestionan para trabajar y responder de forma conjunta. No hay un gestor
para delimitar, asignar y coordinar las tareas. Son los desarrolladores los que
se coordinan. Todos aportan y colaboran con el propietario del producto en el
desarrollo de la pila del producto, participan en la toma de decisiones, y
respetan las opiniones y aportes de los demás. Comparten el objetivo de cada
sprint y la responsabilidad del logro. Por último, todos están familiarizados
con scrum.
Colaborador comprometido: intervienen directamente en la construcción del producto o el
desarrollo del servicio.
Colaboradores implicados: otras partes interesadas, tales como dirección, gerencia,
comerciales, marketing, operadores del sistema que se desarrolla, soporte a
usuarios.

**Comment by Lorenacalvoperez** [comment]
Todo perfecto y completado
