### ISSUE TITLE
Glosario de términos

### ISSUE THREAD

**Issue by Lorenacalvoperez** [Mariosutil/Ing_Gest_Poyectos#6]
Realizar un glosario de entre 8 y 15 conceptos más interesantes a cerca del capítulo

**Comment by Mariosutil** [comment]
**Este es mi glosario:**

- **Entrega de valor**: principio de scrum que se basa en la pronta y continua entrega de valor al cliente, quien colabora con el equipo compartiendo su visión.

- **Operativa visible**: principio de scrum que se basa en compartir la información con claridad para facilitar la colaboración e identificar impedimentos tempranamente y permitir a todo el equipo conocer el estado del producto y aportar ideas.

- **Cultura de empresa**: consiste en la suma de las características organizacionales y de gobernanza de la empresa, que aceleran o frenan su ágil desarrollo.

- **Propietario del producto o product owner**: responsable de la pila del producto, gestionando y priorizando los requisitos y haciendo los cambios necesarios para una pronta y continua entrega del valor. Representa al cliente y comunica la visión de éste al equipo. 

- **Desarrolladores**: responsables de mejorar los resultados y métodos, comprometiéndose con su trabajo y favoreciendo con su talento e inteligencia colectiva al cliente. 

- **Pila del sprint**: artefacto que delimita el trabajo de un incremento, marca el avance y favorece la comunicación interna del equipo, permitiendo que de un vistazo se conozca el estado del sprint. 

- **Retrospectiva del sprint**: evento que sirve para analizar los métodos de trabajo del equipo y permite decidir qué se tiene que mantener, modificar o eliminar.

- **Kanban**: técnica que gestiona visualmente un flujo continuo de avance sin dividir el trabajo en sprints de duración predeterminada. Las anotaciones del equipo sobre las tareas o historias de usuario se posicionan en un tablero y así se determina su estado, siendo una útil herramienta para compartir información. 

- **Gráfico del producto o burn up**: herramienta de planificación propia del propietario del producto, que representa la evolución previsible según la velocidad del equipo de trabajo, mostrándose las previsiones tras cada evolución de la pila del producto.

- **Diagrama de árbol**: práctica para flexibilizar scrum, que utiliza un diagrama para retrospectivas, con el fin de llegar a conclusiones positivas tras el análisis de un problema, donde los elementos del árbol representan los recursos empleados para solucionarlo y ver los resultados posibles.

**Comment by Mariosutil** [comment]
Si me dais el visto bueno cierro la tarea.

**Comment by Lorenacalvoperez** [comment]
Esta todo perfecto
