### ISSUE TITLE
Diagrama Conceptual

### ISSUE THREAD

**Issue by pgl1005** [Mariosutil/Ing_Gest_Poyectos#7]
Poner un diagrama conceptual sobre lo más importante del capítulo

**Comment by pgl1005** [comment]
Este es el diagrama conceptual sobre el capítulo 1:
![image](https://user-images.githubusercontent.com/127233991/230456598-a68a62d7-f68b-4887-9cdc-8d0b879c517a.png)

**Comment by Mariosutil** [comment]
Perfecto, lo veo bien. Si quieres podemos cerrar la tarea.

**Comment by pgl1005** [comment]
Si, cerramos la tarea.
