### ISSUE TITLE
Diagrama conceptual

### ISSUE THREAD

**Issue by Mariosutil** [Mariosutil/Ing_Gest_Poyectos#8]
Escoger algún diagrama conceptual que parezca interesante acerca del capítulo 02.

**Comment by Lorenacalvoperez** [comment]
He encotrado dos diagramas que podrían reunir los conceptos del capítulo dos, los inserto por separado y me decís cual creéis que puede ser el más adecuado

**Comment by Lorenacalvoperez** [comment]
![image](https://user-images.githubusercontent.com/127235680/230457325-4bc8bfec-82ee-46e5-8e54-bea3dd90eef2.png)

**Comment by Lorenacalvoperez** [comment]
![image](https://user-images.githubusercontent.com/127235680/230457381-42840db6-ac25-4522-8219-f15266f21178.png)

**Comment by JuliaArellano** [comment]
Ami me gustan los dos

**Comment by JuliaArellano** [comment]
con uno solo no se explica el capitulo

**Comment by JuliaArellano** [comment]
yo elegiria los dos

**Comment by Mariosutil** [comment]
El segundo diagrama también está muy completo, ya que, también incluye los principios y roles de scrum, que son tratados en el capítulo 3. Creo que podríamos poner los dos diagramas.
