### ISSUE TITLE
Preguntas de comprensión

### ISSUE THREAD

**Issue by pgl1005** [Mariosutil/Ing_Gest_Poyectos#9]
Escribir de 1 a 5 preguntas de comprensión sobre el capítulo.

**Comment by JuliaArellano** [comment]
¿Se podría comenzar a realizar el proyecto sin haberse leído inicialmente el manual? Se recomienda que los participantes antes de realizar el proyecto que se lean el manual para realizar el trabajo de forma ágil

**Comment by pgl1005** [comment]
Muy buena pregunta, estas son las que he planteado yo.

-	**¿En qué se basa la gestión predictiva?**
En el inicio se obtiene el resultado final del producto cumpliendo el plazo y los recursos que se acuerden.
-	**¿En qué tipo de modelo de gestión está inspirado Scrum?**
Gestión ágil.
-	**¿Qué características importantes tiene Scrum?**
Equipos que comparten sus conocimientos, desarrollo incremental, calidad depende del conocimiento de las personas y de su creatividad, solapamiento de fases.

**Comment by pgl1005** [comment]
Aquí están las preguntas juntas:  

-	**¿En qué se basa la gestión predictiva?**
En el inicio se obtiene el resultado final del producto cumpliendo el plazo y los recursos que se acuerden.
-	**¿En qué tipo de modelo de gestión está inspirado Scrum?**
Gestión ágil.
-	**¿Qué características importantes tiene Scrum?**
Equipos que comparten sus conocimientos, desarrollo incremental, calidad depende del conocimiento de las personas y de su creatividad, solapamiento de fases.
-  **¿Se podría comenzar a realizar el proyecto sin haberse leído inicialmente el manual?** 
Se recomienda que los participantes antes de realizar el proyecto que se lean el manual para realizar el trabajo de forma ágil

**Comment by Mariosutil** [comment]
Me parecen buenas esas preguntas!!!
